module CifraClub
  # Kicks off crawling of multiple Cifra Club artists by enqueueing jobs for each one.
  #
  # Usage:
  #   CifraClub::CrawlArtistsJob.perform_later
  #   CifraClub::CrawlArtistsJob.perform_later(artist_urls: ["https://www.cifraclub.com.br/legiao-urbana/"])
  #   CifraClub::CrawlArtistsJob.perform_later(max_songs: 20)
  #
  class CrawlArtistsJob < ApplicationJob
    queue_as :default

    # Retry with exponential backoff on network errors
    retry_on CifraClub::PageScraper::FetchError, wait: :polynomially_longer, attempts: 3

    def perform(artist_urls: nil, max_songs: 15)
      artist_urls ||= default_artist_urls

      Rails.logger.info "[CC Crawl] Starting artist crawl for #{artist_urls.size} artists (max #{max_songs} songs per artist)"

      artist_urls.each_with_index do |artist_url, index|
        # Stagger jobs to be polite to Cifra Club servers (10 second delay between artists)
        CrawlArtistJob.set(wait: (index * 10).seconds).perform_later(
          url: artist_url,
          max_songs: max_songs
        )
      end

      Rails.logger.info "[CC Crawl] Enqueued #{artist_urls.size} artist crawl jobs"
    end

    private

    def default_artist_urls
      [
        "https://www.cifraclub.com.br/anavitoria/",
        "https://www.cifraclub.com.br/armandinho/",
        "https://www.cifraclub.com.br/almir-sater/",
        "https://www.cifraclub.com.br/adoniran-barbosa/",
        "https://www.cifraclub.com.br/ana-castela/",
        "https://www.cifraclub.com.br/alcione/",
        "https://www.cifraclub.com.br/alceu-valenca/",
        "https://www.cifraclub.com.br/amado-batista/",
        "https://www.cifraclub.com.br/arlindo-cruz/",
        "https://www.cifraclub.com.br/adriana-calcanhotto/",
        "https://www.cifraclub.com.br/art-popular/",
        "https://www.cifraclub.com.br/ana-carolina/",
        "https://www.cifraclub.com.br/ana-vilela/",
        "https://www.cifraclub.com.br/bruno-e-marrone/",
        "https://www.cifraclub.com.br/belo/",
        "https://www.cifraclub.com.br/barao-vermelho/",
        "https://www.cifraclub.com.br/banda-eva/",
        "https://www.cifraclub.com.br/biquini-cavadao/",
        "https://www.cifraclub.com.br/bezerra-da-silva/",
        "https://www.cifraclub.com.br/benito-di-paula/",
        "https://www.cifraclub.com.br/beth-carvalho/",
        "https://www.cifraclub.com.br/beto-guedes/",
        "https://www.cifraclub.com.br/chitaozinho-e-xororo/",
        "https://www.cifraclub.com.br/caetano-veloso/",
        "https://www.cifraclub.com.br/capital-inicial/",
        "https://www.cifraclub.com.br/chico-buarque/",
        "https://www.cifraclub.com.br/cesar-menotti-e-fabiano/",
        "https://www.cifraclub.com.br/cartola/",
        "https://www.cifraclub.com.br/calcinha-preta/",
        "https://www.cifraclub.com.br/cpm-22/",
        "https://www.cifraclub.com.br/charlie-brown-jr/",
        "https://www.cifraclub.com.br/cassia-eller/",
        "https://www.cifraclub.com.br/cazuza/",
        "https://www.cifraclub.com.br/chiclete-com-banana/",
        "https://www.cifraclub.com.br/cidade-negra/",
        "https://www.cifraclub.com.br/catedral/",
        "https://www.cifraclub.com.br/daniel/",
        "https://www.cifraclub.com.br/delacruz/",
        "https://www.cifraclub.com.br/djavan/",
        "https://www.cifraclub.com.br/detonautas/",
        "https://www.cifraclub.com.br/dilsinho/",
        "https://www.cifraclub.com.br/diogo-nogueira/",
        "https://www.cifraclub.com.br/engenheiros-do-hawaii/",
        "https://www.cifraclub.com.br/eli-soares/",
        "https://www.cifraclub.com.br/elis-regina/",
        "https://www.cifraclub.com.br/edu-ribeiro/",
        "https://www.cifraclub.com.br/exaltasamba-musicas/",
        "https://www.cifraclub.com.br/edson-e-hudson/",
        "https://www.cifraclub.com.br/erasmo-carlos/",
        "https://www.cifraclub.com.br/emilio-santiago/",
        "https://www.cifraclub.com.br/elba-ramalho/",
        "https://www.cifraclub.com.br/ed-motta/",
        "https://www.cifraclub.com.br/fernando-sorocaba/",
        "https://www.cifraclub.com.br/frejat/",
        "https://www.cifraclub.com.br/flavio-venturini/",
        "https://www.cifraclub.com.br/fresno/",
        "https://www.cifraclub.com.br/fabio-jr/",
        "https://www.cifraclub.com.br/falamansa/",
        "https://www.cifraclub.com.br/fagner/",
        "https://www.cifraclub.com.br/gusttavo-lima/",
        "https://www.cifraclub.com.br/revelacao/",
        "https://www.cifraclub.com.br/fundo-de-quintal/",
        "https://www.cifraclub.com.br/guilherme-e-santiago/",
        "https://www.cifraclub.com.br/gal-costa/",
        "https://www.cifraclub.com.br/gonzaguinha/",
        "https://www.cifraclub.com.br/guilherme-arantes/",
        "https://www.cifraclub.com.br/gilsons/",
        "https://www.cifraclub.com.br/gino-e-geno/",
        "https://www.cifraclub.com.br/gilberto-gil/",
        "https://www.cifraclub.com.br/gian-e-giovanni/",
        "https://www.cifraclub.com.br/grupo-menos-e-mais/",
        "https://www.cifraclub.com.br/henrique-e-juliano/",
        "https://www.cifraclub.com.br/humberto-gessinger/",
        "https://www.cifraclub.com.br/harmonia-do-samba/",
        "https://www.cifraclub.com.br/hungria-hip-hop/",
        "https://www.cifraclub.com.br/ivete-sangalo/",
        "https://www.cifraclub.com.br/ivyson/",
        "https://www.cifraclub.com.br/ira/",
        "https://www.cifraclub.com.br/ivan-lins/",
        "https://www.cifraclub.com.br/iza/",
        "https://www.cifraclub.com.br/jota-quest/",
        "https://www.cifraclub.com.br/jorge-vercillo/",
        "https://www.cifraclub.com.br/jorge-ben-jor/",
        "https://www.cifraclub.com.br/joao-bosco-viniciusacustico/",
        "https://www.cifraclub.com.br/jao/",
        "https://www.cifraclub.com.br/joao-gomes/",
        "https://www.cifraclub.com.br/jorge-aragao/",
        "https://www.cifraclub.com.br/jorge-mateus/",
        "https://www.cifraclub.com.br/katinguele/",
        "https://www.cifraclub.com.br/klb/",
        "https://www.cifraclub.com.br/kid-abelha/",
        "https://www.cifraclub.com.br/legiao-urbana/",
        "https://www.cifraclub.com.br/luiz-gonzaga/",
        "https://www.cifraclub.com.br/lulu-santos/",
        "https://www.cifraclub.com.br/leandro-e-leonardo/",
        "https://www.cifraclub.com.br/luan-santana/",
        "https://www.cifraclub.com.br/los-hermanos/",
        "https://www.cifraclub.com.br/leonardo/",
        "https://www.cifraclub.com.br/lagum/",
        "https://www.cifraclub.com.br/ls-jack/",
        "https://www.cifraclub.com.br/milionario-e-jose-rico/",
        "https://www.cifraclub.com.br/mamonas-assassinas/",
        "https://www.cifraclub.com.br/maiara-maraisa/",
        "https://www.cifraclub.com.br/martinho-da-vila/",
        "https://www.cifraclub.com.br/melim/",
        "https://www.cifraclub.com.br/marcos-belutti/",
        "https://www.cifraclub.com.br/marisa-monte/",
        "https://www.cifraclub.com.br/marilia-mendonca/",
        "https://www.cifraclub.com.br/matheus-kauan/",
        "https://www.cifraclub.com.br/milton-nascimento/",
        "https://www.cifraclub.com.br/maneva/",
        "https://www.cifraclub.com.br/maria-bethania/",
        "https://www.cifraclub.com.br/natiruts/",
        "https://www.cifraclub.com.br/nando-reis/",
        "https://www.cifraclub.com.br/ney-matogrosso/",
        "https://www.cifraclub.com.br/nelson-cavaquinho/",
        "https://www.cifraclub.com.br/netinho/",
        "https://www.cifraclub.com.br/os-novos-baianos/",
        "https://www.cifraclub.com.br/nenhum-de-nos/",
        "https://www.cifraclub.com.br/nelson-goncalves/",
        "https://www.cifraclub.com.br/nx-zero/",
        "https://www.cifraclub.com.br/negritude-junior/",
        "https://www.cifraclub.com.br/os-paralamas-do-sucesso/",
        "https://www.cifraclub.com.br/onze20/",
        "https://www.cifraclub.com.br/o-terno/",
        "https://www.cifraclub.com.br/os-travessos/",
        "https://www.cifraclub.com.br/olodum/",
        "https://www.cifraclub.com.br/oswaldo-montenegro/",
        "https://www.cifraclub.com.br/mutantes/",
        "https://www.cifraclub.com.br/o-teatro-magico/",
        "https://www.cifraclub.com.br/oriente/",
        "https://www.cifraclub.com.br/o-rappa/",
        "https://www.cifraclub.com.br/os-baroes-da-pisadinha/",
        "https://www.cifraclub.com.br/os-garotin/",
        "https://www.cifraclub.com.br/odair-jose/",
        "https://www.cifraclub.com.br/pineapple/",
        "https://www.cifraclub.com.br/paulinho-moska/",
        "https://www.cifraclub.com.br/pitty/",
        "https://www.cifraclub.com.br/pericles/",
        "https://www.cifraclub.com.br/pixote/",
        "https://www.cifraclub.com.br/pollo/",
        "https://www.cifraclub.com.br/planta-e-raiz/",
        "https://www.cifraclub.com.br/paula-fernandes/",
        "https://www.cifraclub.com.br/papas-na-lingua/",
        "https://www.cifraclub.com.br/raul-seixas/",
        "https://www.cifraclub.com.br/raca-negra/",
        "https://www.cifraclub.com.br/rita-lee/",
        "https://www.cifraclub.com.br/raimundos/",
        "https://www.cifraclub.com.br/renato-russo/",
        "https://www.cifraclub.com.br/rubel/",
        "https://www.cifraclub.com.br/reginaldo-rossi/",
        "https://www.cifraclub.com.br/rick-e-renner/",
        "https://www.cifraclub.com.br/roupa-nova/",
        "https://www.cifraclub.com.br/roberto-carlos/",
        "https://www.cifraclub.com.br/rio-negro-e-solimoes/",
        "https://www.cifraclub.com.br/rpm/",
        "https://www.cifraclub.com.br/restart/",
        "https://www.cifraclub.com.br/skank/",
        "https://www.cifraclub.com.br/so-pra-contrariar/",
        "https://www.cifraclub.com.br/sorriso-maroto/",
        "https://www.cifraclub.com.br/system-of-a-down/",
        "https://www.cifraclub.com.br/seu-jorge/",
        "https://www.cifraclub.com.br/sandy-e-junior-musicas/",
        "https://www.cifraclub.com.br/soweto/",
        "https://www.cifraclub.com.br/simone-simaria-as-coleguinhas/",
        "https://www.cifraclub.com.br/secos-molhados/",
        "https://www.cifraclub.com.br/titas/",
        "https://www.cifraclub.com.br/thiaguinho/",
        "https://www.cifraclub.com.br/tiago-iorc/",
        "https://www.cifraclub.com.br/toquinho/",
        "https://www.cifraclub.com.br/tribalistas/",
        "https://www.cifraclub.com.br/tim-maia/",
        "https://www.cifraclub.com.br/tom-jobim/",
        "https://www.cifraclub.com.br/tim-bernardes/",
        "https://www.cifraclub.com.br/tonico-e-tinoco/",
        "https://www.cifraclub.com.br/turma-do-pagode/",
        "https://www.cifraclub.com.br/um44k/",
        "https://www.cifraclub.com.br/ultraje-a-rigor/",
        "https://www.cifraclub.com.br/victor-leo/",
        "https://www.cifraclub.com.br/ventania/",
        "https://www.cifraclub.com.br/vanessa-da-mata/",
        "https://www.cifraclub.com.br/vitor-kley/",
        "https://www.cifraclub.com.br/vinicius-de-moraes/",
        "https://www.cifraclub.com.br/walmir-alencar/",
        "https://www.cifraclub.com.br/wesley-safadao/",
        "https://www.cifraclub.com.br/whindersson-nunes/",
        "https://www.cifraclub.com.br/mc-xama/",
        "https://www.cifraclub.com.br/xande-de-pilares/",
        "https://www.cifraclub.com.br/xuxa/",
        "https://www.cifraclub.com.br/zeze-di-camargo-e-luciano/",
        "https://www.cifraclub.com.br/zeca-pagodinho/",
        "https://www.cifraclub.com.br/zimbra/",
        "https://www.cifraclub.com.br/zizi-possi/",
        "https://www.cifraclub.com.br/zeca-baleiro/",
        "https://www.cifraclub.com.br/ze-ramalho/",
        "https://www.cifraclub.com.br/zelia-duncan/",
        "https://www.cifraclub.com.br/zelda/",
        "https://www.cifraclub.com.br/1kilo/",
        "https://www.cifraclub.com.br/14-bis/",
        "https://www.cifraclub.com.br/5-seco/",
        "https://www.cifraclub.com.br/3030/"
      ]
    end
  end
end
